# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"  # Python uses pip for dependency management
    directory: "/"  # Root directory (change if dependencies are in a subdirectory)
    schedule:
      interval: "weekly"  # Options: daily, weekly, monthly
    open-pull-requests-limit: 5  # Maximum number of open PRs
    ignore:
      - dependency-name: "numpy"  # Ignore updates for numpy
        versions: ["1.22.0"]  # Ignore specific version(s)
    groups:
      dev-dependencies:
        patterns:
          - "pytest"  # Group all pytest-related updates
          - "black"
      security-updates:
        dependency-type: "development"  # Specify the dependency type
        applies-to: security-updates  # Group security-related updates
    commit-message:
      prefix: "[DepBot]"  # Custom PR commit prefix
      include: "scope"  # Includes dependency scope in commit message
